# Generated by Django 3.1.5 on 2021-01-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210124_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpost',
            name='description',
            field=models.CharField(default=' ', max_length=350),
        ),
        migrations.AddField(
            model_name='vendorpost',
            name='email',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
